# Site settings
title: "Blog Arie"
header-img: img/home-bg.jpg
email: aakarie18@gmail.com
copyright_name: "Ario Blog"
description: "Slow but sure!"
baseurl: ""

# github
url: "https://aak-arie.github.io"

# localhost
#url: "http://localhost:4000"

# twitter_username: SBootstrap
github_username: aak-arie
facebook_username: Arioo
ig_username: ariio77
email_username: aakarie18@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
